# Generated by Django 2.2 on 2021-10-24 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='nombre',
            new_name='name',
        ),
    ]
