# Generated by Django 2.2 on 2021-10-24 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211023_2134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='client',
            new_name='client_id',
        ),
    ]
