# Generated by Django 2.2 on 2021-10-30 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_invoice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='currency',
            new_name='currency_id',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='plan',
            new_name='plan_id',
        ),
    ]
