# Generated by Django 2.2 on 2021-10-24 06:30

from django.db import migrations, models
import main.models.invoice


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20211023_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='file',
            field=models.ImageField(upload_to=main.models.invoice.upload_invoice),
        ),
    ]
