# Generated by Django 2.2 on 2021-10-25 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20211024_0047'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comission',
            new_name='Commission',
        ),
    ]
