# Generated by Django 2.2 on 2021-10-25 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20211025_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='brand_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Brand'),
        ),
        migrations.AddField(
            model_name='investment',
            name='client_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Client'),
        ),
    ]
